### ISSUE TITLE
Image slideshow in device page does not work.

### ISSUE THREAD

**Issue by wellaDIN** [wellaDIN/wei#21]
The image slideshow in the device page is not working.
If you just put the code in the .html page it works, but our need is to create dynamically the `<li>`elements in the `<ul>`element in the device.js.
Right now the script actually creates the `<li>` element, but it looks like the html page does not put those elements in the slideshow, even if they are in the `<ul>` list.

Asking help to @francescorinaldi

**Comment by wellaDIN** [comment]
I don't know if this can be of any help, but I had a similar problem when dealing with the tab panel for the Assistance Service: there you had to add new tabs dynamically and then the script would have changed the panel depending on the clicked tab.
Well, at the first attempt the situation was like this one: the tabbed (images, here) were created, but after the click nothing happened. I realized that the problem was in the fact that the **new** elements were not considered by the script managing the tab click (indeed the old tabs worked fine). I hence used again the script **after** creating the new tabs in the .js file and it worked.
I think the strategy here should be the same: after creating the `<li>` elements, you should run again the script which manages the image clicking.

**Comment by francescorinaldi** [comment]
Solved.

**Comment by francescorinaldi** [comment]
To solve this issue we create 5 <li> elements with a different ID in the HTML page and, for every device, we dynamically assign by jquery the images to it according to its name and to the number of images for each device.
